services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: local_pgdb
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:5.0-alpine3.10
    ports:
      - "6379:6379"
    container_name: local_redis
    volumes:
      - local_redisdata:/path/to/local/d–∞ta:/root/redis
    environment:
      REDIS_PASSWORD: redis

  backend-express:
    depends_on:
      - db
    container_name: local_backend
    build: ./result
    ports:
      - "4000:4000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: resultdb

  frontend-python:
    depends_on:
      - backend-express
    container_name: local_frontend
    environment:
      REDIS_HOST: redis
    build: ./vote
    ports:
      - "5000:80"

  worker:
    build: ./worker
    depends_on:
      - redis
      - db

volumes:
  local_pgdata:
  local_redisdata:




